can u check this!
fcs-cs/cs2-student-files pull request #21
Opened 2019-02-25 14:59 UTC by awualex

,,,,

2019-02-25 15:00 UTC, Mr-Darfler commented on Class-Code/Elementary-CA/awu/sketch.js
>  //Project Name
Make Sure you Add in the project name and Date

2019-02-25 15:01 UTC, Mr-Darfler commented on Class-Code/Elementary-CA/awu/sketch.js
> +function ruleset(uno, dos, tres) {
Naming convention is a bit odd. consider more descriptive  names

2019-02-25 15:02 UTC, Mr-Darfler reviewed
@awualex I Made some comments. take a look

2019-02-25 15:02 UTC, Mr-Darfler commented on Class-Code/Elementary-CA/awu/sketch.js
> +    gen_0 = gen_new ;}
I don't think you need to re assign gen_0

2019-02-25 15:03 UTC, Mr-Darfler requested changes
please change code

2019-02-25 19:34 UTC, awualex commented
Now it works ;0

2019-02-27 15:27 UTC, Mr-Darfler approved these changes

2019-02-27 15:34 UTC, Mr-Darfler commented
Alex, please 

- remove you commented draw() function
- update your existing draw() function to look more like
```
function draw(){
    display();
    generate();
    scrol();
```
- take the code from your existing draw() function and turn them into the functions above. This will help clean up your code and make it easier to read.

2019-02-28 19:52 UTC, Mr-Darfler commented
Closing pull request until final commit

2019-02-28 19:52 UTC, closed without merging