Working CA
fcs-cs/cs2-student-files pull request #29
Opened 2019-03-04 18:45 UTC by Jkohl1

2019-03-06 13:57 UTC, pryan4 commented on Class-Code/Elementary-CA/jkohl/sketch.js
> -//Your Name(s)
need header

2019-03-06 13:58 UTC, pryan4 commented on Class-Code/Elementary-CA/jkohl/sketch.js
> +    //generate
don't need these

2019-03-06 13:58 UTC, pryan4 commented on Class-Code/Elementary-CA/jkohl/sketch.js
> +    //display
remove

2019-03-06 13:58 UTC, pryan4 commented on Class-Code/Elementary-CA/jkohl/sketch.js
> +
need a background command

2019-03-06 19:39 UTC, Mr-Darfler requested changes
You're pretty close @Jkohl1 Make sure that you add the header info

2019-03-06 19:39 UTC, Mr-Darfler commented on Class-Code/Elementary-CA/jkohl/sketch.js
> -
Make sure to include:
- Name
- Project Name
- Date
- A brief description of the code

2019-03-06 19:39 UTC, Mr-Darfler commented on Class-Code/Elementary-CA/jkohl/sketch.js
> +    //display
If you're not going to turn all of this into a function, I would leave in the comment

2019-03-06 19:39 UTC, Mr-Darfler commented on Class-Code/Elementary-CA/jkohl/sketch.js
> +    //generate
Again, I think leaving the comment does help structure the code

2019-03-07 17:07 UTC, fcsmakers approved these changes

2019-03-07 17:08 UTC, Mr-Darfler approved these changes

2019-03-07 17:08 UTC, merged