Final
fcs-cs/cs2-student-files pull request #34
Opened 2019-03-14 13:00 UTC by Jkohl1

2019-03-14 13:06 UTC, pryan4 reviewed
looks good.

2019-03-15 13:49 UTC, Mr-Darfler requested changes
The functionality is there, Jacob, but there are still some formatting issues to take care of. Please correct before I pull

2019-03-15 13:49 UTC, Mr-Darfler commented on Class-Code/Game of Life/jkohl/sketch.js
> +        current.push(new Array(columns).fill(0).map(()=>round(random())))
This line is long. Might look better as
```
for(let row = 0; row < rows; row++){
    current.push(
        new Array(columns)
        .fill(0)
        .map(()=>round(random()))
    )
}
```

2019-03-15 13:49 UTC, Mr-Darfler commented on Class-Code/Game of Life/jkohl/sketch.js
> +    //noLoop()
A comment here would be good. What's happening here if you are already initializing the board with random 0's and 1's

2019-03-15 13:49 UTC, Mr-Darfler commented on Class-Code/Game of Life/jkohl/sketch.js
> +        current.push(new Array(columns).fill(0).map(()=>round(random())))
Also, this could use a comment or could be turned into a function for clarity's sake. i.e. what is your intent with this loop

2019-03-15 13:49 UTC, Mr-Darfler commented on Class-Code/Game of Life/jkohl/sketch.js
> +    let nextgen = [];
Everything below could get turned into a function called `generate()`

2019-03-18 17:37 UTC, Mr-Darfler approved these changes

2019-03-18 17:37 UTC, Mr-Darfler commented
@pryan4 Please finish your review

2019-03-19 21:42 UTC, pryan4 approved these changes

2019-04-10 12:10 UTC, merged